abstract class AppStates {}
class AppInitialStates extends AppStates{}
class AppChangeBottonNavBarState extends AppStates{}
class AppCreateDatabaseState extends AppStates{}
class AppInsertDatabasState extends AppStates{}
class AppGetDatabasState extends AppStates{}
class AppUpdateDatabasState extends AppStates{}
class AppDeleteDatabasState extends AppStates{}
class AppGetDatabasLoadingState extends AppStates{}
class AppChangeIconBottomSheetState extends AppStates{}
class AppChangeModeState extends AppStates{}
